### ISSUE TITLE
Cardidy failed with JCB cards and Diners club cards

### ISSUE THREAD

**Issue by merge-tek** [d-edge/Cardidy#111]
Hello, I tried with the following credit cards numbers

JCB: 3530111333300000, 3566002020360505
Diners: 30569309025904,   3056930009020004

Also, I tried with this Credit Card Generator [https://www.vccgenerator.org/](url), [https://www.validcreditcardnumber.com/](url), and choose JCB or Diners Club options to generated, and all failed

The error I get is a `Sequence contains more than one element`

with `DEdge.Cardidy.Identify(cardNumber).Single();`

<img width="962" alt="image" src="https://user-images.githubusercontent.com/107663367/208808835-7663e424-b575-4a1c-8177-63be4443d56d.png">

**Comment by torendil** [comment]
Hi!

**Comment by torendil** [comment]
Hi @merge-tek !

First of all, thanks for using Cardidy!

For the first situation regarding JCB, it's because those cards could also be a RuPay card. We ordered them in an order that seemed like the most likely use of cards, hence why you'll find that JCB is the first one that gets out of the Identify method, but not the only one
Please use First() instead of Single :)

For Diner's Club International, the IIN should start with 36, so it is normal you wouldn't find a match with a card that starts with 30. Could you please tell me the configuration you used to get something else than 36 as a prefix?

By the way, if you know there is a range that is not in the [Wiki page](https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_(IIN)), please update the wikipedia and you can also contribute to the library by opening a PR :)

With my best

**Comment by aloisdg** [comment]
Hi! Here is a a small demo showcasing @torendil's excellent answer:

```csharp
using System;
using System.Linq;
using DEdge;

public class Program
{
	public static void Main()
	{
		var cardNumber = "3530111333300000";
		// this line will fail because this card number can be either a JCB or RuPay card
		// var result = Cardidy.Identify(cardNumber).Single();
		// try this instead
		var result = Cardidy.Identify(cardNumber).First();
		Console.WriteLine(result);
		// or even
		foreach (var card in Cardidy.Identify(cardNumber))
		{
			Console.WriteLine($"cardNumber can be {card}");
		}
	}
}
```

https://dotnetfiddle.net/2yHfZQ

**Comment by aloisdg** [comment]
Let's close this one for now. Feel free to open a new question if you have one.
